import Navbar from '../components/Navbar'; 
import './globals.css'
import React from 'react';


export const metadata = {
  title: 'Wind Form',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <React.StrictMode>
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
    </React.StrictMode>
  )
}
