import Navbar from './components/navbar'
import './globals.css'
import Sidebar from './Sidebar';
import { useRouter } from 'next/router';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter();
  const isDocumentationPage = router.pathname === '/docs';
  return (
    <html lang="en">
      <body className={''}>
        <Navbar />
        {isDocumentationPage && <Sidebar />}
        {children}
      </body>
    </html>
  )
}
